### PR TITLE
align T3DVec4, typedef it as T3DQuat and fix swapped vector/matrix comment

### PR DESCRIPTION
**Pull request by jopadan**

### CODE REVIEW

**Comment by HailToDodongo** [comment]
What is the use-case for aligning the vector?
In itself it doesn't need it and it may even waste a few bytes if part of a bigger struct. There should also be nothing that DMA's it with alignment restrictions like the RSP would for the fixed-point matrix.

As for the typedef, i do want to hold back on that for now.
I'm currently starting to add some function- and operator-overloads for better c++ compat where i would need distinct types.

**Comment by jopadan** [comment]
Maybe you should switch to a [kokkos/mdarray](https://github.com/kokkos/mdarray) [kokkos/mdspan](https://github.com/kokkos/mdspan) inspired implementation for C++

**Comment by HailToDodongo** [comment]
Could you explain what what you mean?
I don't see the connection to the C++ part.

In any case, the other issues regarding alignment are still an issue.
So i would just want to know why you need the T3DVec4 aligned to 16 bytes?

**Comment by jopadan** [comment]
The [SGI Nintendo 64 RSP_Programmers_Guide](https://ultra64.ca/files/documentation/silicon-graphics/SGI_Nintendo_64_RSP_Programmers_Guide.pdf) states that there are 3 different alignment methods normal, packed requiring element size alignment and transpose requiring vector size alignment along with 8 byte alignment for RSP DMA.
Like other SIMD and vector type implementations the float4 should be a 16 byte aligned.
This restricts vector types not to be linear movable by one element at a time in memory.

**Comment by HailToDodongo** [comment]
This has nothing to do with T3DVec3, what you cite refers to the RSP, not CPU.
T3DVec3 only exists on the CPU (which has no SIMD) and is never used by the RSP

**Pull request closed without merging**
